/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pt.ua.ibank.interfaces.internalFrames.staff.profile.personal;

import java.awt.event.ActionEvent;
import pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilTableActionEvent;

/**
 *
 * @author ricar
 */
public class PerfilActionPanelElement extends javax.swing.JPanel {

    /**
     * Creates new form ClientProfilePanelAction
     */
    String data;

    public PerfilActionPanelElement() {
        initComponents();
        data = "";
        jTextFieldNewValue.setVisible(false);
        cmdCancel.setVisible(false);
        cmdSave.setVisible(false);
        cmdEdit.setLocation(cmdCancel.getLocation());
    }

    public PerfilActionPanelElement(String initialValue) {
        initComponents();
        this.data = initialValue;
        jTextFieldNewValue.setVisible(false);
        cmdCancel.setVisible(false);
        cmdSave.setVisible(false);
        cmdEdit.setLocation(cmdCancel.getLocation());
    }

    public void InitEvent(PerfilTableActionEvent event, int row) {
        cmdEdit.addActionListener((ActionEvent e) -> {
            jTextFieldNewValue.setText(data);
            event.onEdit(row);

        });
        cmdSave.addActionListener((ActionEvent e) -> {
            String newValue = jTextFieldNewValue.getText();
            data = newValue;
            event.onSave(row, newValue);
        });
        cmdCancel.addActionListener((ActionEvent e) -> {
            event.onCancel(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNewValue = new javax.swing.JTextField();
        cmdEdit = new pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilActionButton();
        cmdSave = new pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilActionButton();
        cmdCancel = new pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilActionButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextFieldNewValue.setToolTipText("eeeee");
        jTextFieldNewValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewValueActionPerformed(evt);
            }
        });

        cmdEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/edit.png"))); // NOI18N

        cmdSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/tick.png"))); // NOI18N
        cmdSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveActionPerformed(evt);
            }
        });

        cmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/cancel.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextFieldNewValue, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNewValue)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(cmdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditActionPerformed
        cmdCancel.setVisible(true);
        cmdSave.setVisible(true);
        cmdEdit.setVisible(false);
        jTextFieldNewValue.setVisible(true);
    }//GEN-LAST:event_cmdEditActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        cmdCancel.setVisible(false);
        cmdSave.setVisible(false);
        cmdEdit.setVisible(true);
        jTextFieldNewValue.setVisible(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveActionPerformed
        cmdCancel.setVisible(false);
        cmdSave.setVisible(false);
        cmdEdit.setVisible(true);
        jTextFieldNewValue.setVisible(false);
    }//GEN-LAST:event_cmdSaveActionPerformed

    private void jTextFieldNewValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewValueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilActionButton cmdCancel;
    private pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilActionButton cmdEdit;
    private pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.PerfilActionButton cmdSave;
    private javax.swing.JTextField jTextFieldNewValue;
    // End of variables declaration//GEN-END:variables
}
