/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pt.ua.ibank.interfaces.internalFrames.staff.profile.deposit;

import pt.ua.ibank.interfaces.internalFrames.staff.profile.personal.*;
import java.awt.Color;

/**
 *
 * @author ricar
 */
public class DepositTableElementPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientProfileListElementPanel
     *
     * @param id
     * @param ammount
     * @param wasApproved
     * @param isPending
     */
    public DepositTableElementPanel(String id,
            String ammount, boolean wasApproved) {
        initComponents();
        this.lblIdValue.setText(id);
        this.lblValueInEurosValue.setText(ammount);
        this.lblPendingState.setText(wasApproved ? "aprovada" : "rejeitada");
        Color bgColor = new Color(0xFFFFFFFF);
        this.setBackground(bgColor);
    }

    public DepositTableElementPanel(String id,
            String ammount) {
        initComponents();
        this.lblIdValue.setText(id);
        this.lblValueInEurosValue.setText(ammount);
        this.lblPendingState.setText("");
        Color bgColor = new Color(0xFFFFFFFF);
        this.setBackground(bgColor);
    }

    public DepositTableElementPanel() {
        initComponents();
        this.lblIdValue.setText("69");
        this.lblValueInEurosValue.setText("420");

        Color bgColor = new Color(0xFFFFFFFF);
        this.setBackground(bgColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        lblValueInEuros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIdValue = new javax.swing.JLabel();
        lblValueInEurosValue = new javax.swing.JLabel();
        lblPendingState = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblID.setText("ID:");

        lblValueInEuros.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblValueInEuros.setText("Valor(€): ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/deposit-pending.png"))); // NOI18N

        lblIdValue.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblIdValue.setText("ID");

        lblValueInEurosValue.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblValueInEurosValue.setText("10");

        lblPendingState.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdValue)
                .addGap(3, 3, 3)
                .addComponent(lblValueInEuros)
                .addGap(3, 3, 3)
                .addComponent(lblValueInEurosValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPendingState)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblValueInEuros, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblValueInEurosValue, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblPendingState))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdValue;
    private javax.swing.JLabel lblPendingState;
    private javax.swing.JLabel lblValueInEuros;
    private javax.swing.JLabel lblValueInEurosValue;
    // End of variables declaration//GEN-END:variables
}
