package pt.ua.ibank.interfaces;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.SwingUtilities;
import pt.ua.ibank.DAO.ClientDAO;
import pt.ua.ibank.DTO.Client;
import pt.ua.ibank.utilities.Configs;
import static pt.ua.ibank.utilities.Configs.EMAIL_ERROR_CODE;
import static pt.ua.ibank.utilities.Configs.ERROR_CODE;
import static pt.ua.ibank.utilities.Configs.LocalClient;
import static pt.ua.ibank.utilities.Configs.SUCCESS_CODE;
import pt.ua.ibank.utilities.Hash;

public class dialogLogin extends javax.swing.JDialog {

    public dialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        start();
    }

    private void start() {
        email_input.requestFocus();
        email_input.setBackground(new java.awt.Color(0, 0, 0, 1));
        password_input.setBackground(new java.awt.Color(0, 0, 0, 1));

        Fname.setBackground(new java.awt.Color(0, 0, 0, 1));
        Femail.setBackground(new java.awt.Color(0, 0, 0, 1));
        Fphone.setBackground(new java.awt.Color(0, 0, 0, 1));
        FNif.setBackground(new java.awt.Color(0, 0, 0, 1));
        FPass.setBackground(new java.awt.Color(0, 0, 0, 1));
        FRPass.setBackground(new java.awt.Color(0, 0, 0, 1));
        FAddress.setBackground(new java.awt.Color(0, 0, 0, 1));

        panelCreateAccount.setVisible(false);

        Configs.loadU();
        email_input.setText(Configs.Uname);
        save_email.setSelected(Configs.Usave);
        KeyListeners();
    }

    private void KeyListeners() {
        email_input.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    password_input.requestFocus();
                }
            }
        });

        password_input.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    login.requestFocus();
                    loginActionPerformed(null);
                }
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    email_input.requestFocus();
                }
            }
        });

        login.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                    password_input.requestFocus();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image_1 = new javax.swing.JLabel();
        panel = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        lblLoginEmail = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        lblEmailDot = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        lblPasswordDot = new javax.swing.JLabel();
        save_email = new javax.swing.JCheckBox();
        login = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lblCreateAccount1 = new javax.swing.JLabel();
        see = new javax.swing.JCheckBox();
        panelCreateAccount = new javax.swing.JPanel();
        erro_create = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFphone = new javax.swing.JLabel();
        Fphone = new javax.swing.JTextField();
        lblDotPhone = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FPass = new javax.swing.JPasswordField();
        lblDotPassword = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblRepeatPass = new javax.swing.JLabel();
        FRPass = new javax.swing.JPasswordField();
        lblRepeatPassDot = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        Femail = new javax.swing.JTextField();
        lblDotEmail = new javax.swing.JLabel();
        lblNIF = new javax.swing.JLabel();
        FNif = new javax.swing.JTextField();
        lblNifDot = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        lblFnameDot = new javax.swing.JLabel();
        lblWelcomeMessage = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        FAddress = new javax.swing.JTextField();
        lblAddressDot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        image_1.setBackground(new java.awt.Color(255, 255, 255));
        image_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/logo_png.png"))); // NOI18N

        panel.setBackground(new java.awt.Color(255, 255, 255));

        panelLogin.setBackground(new java.awt.Color(62, 171, 191));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        error.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        error.setForeground(new java.awt.Color(255, 200, 96));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLogin.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 420, 30));

        lblLoginTitle.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginTitle.setText("Login");
        panelLogin.add(lblLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 420, 41));

        lblLoginEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLoginEmail.setForeground(new java.awt.Color(199, 226, 255));
        lblLoginEmail.setText("Email");
        panelLogin.add(lblLoginEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 360, -1));

        email_input.setFont(email_input.getFont().deriveFont(email_input.getFont().getSize()+2f));
        email_input.setForeground(new java.awt.Color(255, 255, 255));
        email_input.setBorder(null);
        panelLogin.add(email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 310, 30));

        lblEmailDot.setForeground(new java.awt.Color(199, 226, 255));
        lblEmailDot.setText("_________________________________________________________________");
        panelLogin.add(lblEmailDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 319, 40));

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitle.setText("Olá! Bem-vindo ao IBank!");
        panelLogin.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 420, -1));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(199, 226, 255));
        lblPassword.setText("Password");
        panelLogin.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 360, -1));

        password_input.setFont(password_input.getFont().deriveFont(password_input.getFont().getSize()+2f));
        password_input.setForeground(new java.awt.Color(255, 255, 255));
        password_input.setBorder(null);
        password_input.setCaretColor(new java.awt.Color(255, 255, 255));
        panelLogin.add(password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 310, 30));

        lblPasswordDot.setForeground(new java.awt.Color(199, 226, 255));
        lblPasswordDot.setText("_________________________________________________________________");
        panelLogin.add(lblPasswordDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 319, 40));

        save_email.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        save_email.setForeground(new java.awt.Color(199, 226, 255));
        save_email.setText("Guardar email");
        save_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_emailActionPerformed(evt);
            }
        });
        panelLogin.add(save_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(62, 171, 191));
        login.setText("LOGIN");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        panelLogin.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 360, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(199, 226, 255));
        jLabel15.setText("Ainda não tem conta?");
        panelLogin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        lblCreateAccount1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCreateAccount1.setForeground(new java.awt.Color(255, 255, 255));
        lblCreateAccount1.setText("Criar Conta");
        lblCreateAccount1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreateAccount1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateAccount1MouseClicked(evt);
            }
        });
        panelLogin.add(lblCreateAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        see.setForeground(new java.awt.Color(255, 255, 255));
        see.setText("Ver");
        see.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeActionPerformed(evt);
            }
        });
        panelLogin.add(see, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 60, 30));

        panel.addTab("Login", panelLogin);

        panelCreateAccount.setBackground(new java.awt.Color(62, 171, 191));
        panelCreateAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        erro_create.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        erro_create.setForeground(new java.awt.Color(255, 200, 96));
        erro_create.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCreateAccount.add(erro_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 420, 20));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Account");
        panelCreateAccount.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 41));

        lblFphone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFphone.setForeground(new java.awt.Color(199, 226, 255));
        lblFphone.setText("Phone Number");
        panelCreateAccount.add(lblFphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 360, -1));

        Fphone.setFont(Fphone.getFont().deriveFont(Fphone.getFont().getSize()+2f));
        Fphone.setForeground(new java.awt.Color(255, 255, 255));
        Fphone.setBorder(null);
        panelCreateAccount.add(Fphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, 30));

        lblDotPhone.setForeground(new java.awt.Color(199, 226, 255));
        lblDotPhone.setText("_________________________________________________________________");
        panelCreateAccount.add(lblDotPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 319, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(199, 226, 255));
        jLabel7.setText("Password");
        panelCreateAccount.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 360, -1));

        FPass.setFont(FPass.getFont().deriveFont(FPass.getFont().getSize()+2f));
        FPass.setForeground(new java.awt.Color(255, 255, 255));
        FPass.setBorder(null);
        FPass.setCaretColor(new java.awt.Color(255, 255, 255));
        panelCreateAccount.add(FPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 310, 30));

        lblDotPassword.setForeground(new java.awt.Color(199, 226, 255));
        lblDotPassword.setText("_________________________________________________________________");
        panelCreateAccount.add(lblDotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 319, 40));

        btnCreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(62, 171, 191));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateAccountMouseClicked(evt);
            }
        });
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        panelCreateAccount.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 360, 40));

        lblRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(199, 226, 255));
        lblRegister.setText("Already have an account?");
        panelCreateAccount.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        panelCreateAccount.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, -1, -1));

        lblRepeatPass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblRepeatPass.setForeground(new java.awt.Color(199, 226, 255));
        lblRepeatPass.setText("Repeat Password");
        panelCreateAccount.add(lblRepeatPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 360, -1));

        FRPass.setFont(FRPass.getFont().deriveFont(FRPass.getFont().getSize()+2f));
        FRPass.setForeground(new java.awt.Color(255, 255, 255));
        FRPass.setBorder(null);
        FRPass.setCaretColor(new java.awt.Color(255, 255, 255));
        panelCreateAccount.add(FRPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 310, 30));

        lblRepeatPassDot.setForeground(new java.awt.Color(199, 226, 255));
        lblRepeatPassDot.setText("_________________________________________________________________");
        panelCreateAccount.add(lblRepeatPassDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 319, 40));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(199, 226, 255));
        lblEmail.setText("Email");
        panelCreateAccount.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 360, -1));

        Femail.setFont(Femail.getFont().deriveFont(Femail.getFont().getSize()+2f));
        Femail.setForeground(new java.awt.Color(255, 255, 255));
        Femail.setBorder(null);
        panelCreateAccount.add(Femail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 310, 30));

        lblDotEmail.setForeground(new java.awt.Color(199, 226, 255));
        lblDotEmail.setText("_________________________________________________________________");
        panelCreateAccount.add(lblDotEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 319, 40));

        lblNIF.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblNIF.setForeground(new java.awt.Color(199, 226, 255));
        lblNIF.setText("NIF");
        panelCreateAccount.add(lblNIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 360, -1));

        FNif.setFont(FNif.getFont().deriveFont(FNif.getFont().getSize()+2f));
        FNif.setForeground(new java.awt.Color(255, 255, 255));
        FNif.setBorder(null);
        panelCreateAccount.add(FNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 310, 30));

        lblNifDot.setForeground(new java.awt.Color(199, 226, 255));
        lblNifDot.setText("_________________________________________________________________");
        panelCreateAccount.add(lblNifDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 319, 40));

        lblFullName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFullName.setForeground(new java.awt.Color(199, 226, 255));
        lblFullName.setText("Full Name");
        panelCreateAccount.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 360, -1));

        Fname.setFont(Fname.getFont().deriveFont(Fname.getFont().getSize()+2f));
        Fname.setForeground(new java.awt.Color(255, 255, 255));
        Fname.setBorder(null);
        panelCreateAccount.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 30));

        lblFnameDot.setForeground(new java.awt.Color(199, 226, 255));
        lblFnameDot.setText("_________________________________________________________________");
        panelCreateAccount.add(lblFnameDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 319, 40));

        lblWelcomeMessage.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("Welcome! Please, please fill the boxes below to create a new account.");
        panelCreateAccount.add(lblWelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 420, -1));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(199, 226, 255));
        lblAddress.setText("Address");
        panelCreateAccount.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 360, -1));

        FAddress.setFont(FAddress.getFont().deriveFont(FAddress.getFont().getSize()+2f));
        FAddress.setForeground(new java.awt.Color(255, 255, 255));
        FAddress.setBorder(null);
        panelCreateAccount.add(FAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 310, 30));

        lblAddressDot.setForeground(new java.awt.Color(199, 226, 255));
        lblAddressDot.setText("_________________________________________________________________");
        panelCreateAccount.add(lblAddressDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 319, 40));

        panel.addTab("Criar conta", panelCreateAccount);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(image_1)
                .addGap(0, 0, 0)
                .addComponent(panel)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image_1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void save_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_emailActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String email = email_input.getText();
        String password = new String(password_input.getPassword());

        if (password.isEmpty() && email.isEmpty()) {
            error.setText("Empty fields!");
            return;
        } else if (email.isEmpty()) {
            email_input.requestFocus();
            error.setText("Email Field is Empty!");
            return;
        } else if (password.isEmpty()) {
            password_input.requestFocus();
            error.setText("Password field is empty!");
            return;
        }

        error.setText("");
        if (save_email.isSelected()) {
            Configs.Uname = email_input.getText();
            Configs.Usave = save_email.isSelected();
            Configs.saveU();
        } else {
            Configs.Uname = "";
            Configs.Usave = false;
            Configs.saveU();
        }

        LocalClient = new Client(email_input.getText(), new String(
                                 password_input.getPassword()));
        if (LocalClient.authenticate()) {
            Configs.loginOK = true;
            this.dispose();
        } else {
            error.setText("Error Authenticating! Wrong Credentials!");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void lblCreateAccount1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateAccount1MouseClicked
        panel.setSelectedIndex(1);
    }//GEN-LAST:event_lblCreateAccount1MouseClicked

    private void btnCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateAccountMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateAccountMouseClicked

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        erro_create.setText("");

        String password = new String(FPass.getPassword());
        String repeatPassword = new String(FRPass.getPassword());

        String regexNome = "^[a-zA-ZáéíóúÁÉÍÓÚäëïöüÄËÏÖÜãõÃÕñÑçÇ\\s'-]+$";
        String regexEmail =
               "^[a-zA-Z0-9_+&*-]+(?:\\." + "[a-zA-Z0-9_+&*-]+)*@" + "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        String regexTelefoneNif = "^\\d{9}$";
        //String emailRegexSimples = "^(.+)@(.+)$";
        String regexPassword = "^.{8,}$";

        Pattern patternNome = Pattern.compile(regexNome);
        Matcher matcherNome = patternNome.matcher(Fname.getText());

        Pattern patternEmail = Pattern.compile(regexEmail);
        Matcher matcherEmail = patternEmail.matcher(Femail.getText());

        Pattern patternPhoneNumberNif = Pattern.compile(regexTelefoneNif);
        Matcher matcherPhoneNumber = patternPhoneNumberNif.matcher(
                Fphone.getText());
        Matcher matcherNIF = patternPhoneNumberNif.matcher(FNif.getText());

        Pattern patternPassword = Pattern.compile(regexPassword);
        Matcher matcherPassword = patternPassword.matcher(password);

        if (Fname.getText().isEmpty() || Femail.getText().isEmpty() || Fphone.getText().isEmpty() || FNif.getText().isEmpty() || password.isEmpty() || repeatPassword.isEmpty()) {
            erro_create.setText(
                    "One or more empty fields! Por favor preencha-os!");
        } else if (!matcherNome.find()) {
            erro_create.setText("Invalid Name!");
            Fname.setText("");
        } else if (!matcherEmail.find()) {
            erro_create.setText("Invalid Email!");
            Femail.setText("");
        } else if (!matcherPhoneNumber.find()) {
            erro_create.setText("Invalid Phone Number!");
            Fphone.setText("");
        } else if (!matcherNIF.find()) {
            erro_create.setText("Invalid NIF!");
            FNif.setText("");
        } else if (!matcherPassword.find()) {
            erro_create.setText(
                    "Invalid Password! Please input at least 8 characters!");
            FPass.setText("");
            FRPass.setText("");
        } else if (!password.equals(repeatPassword)) {
            erro_create.setText("Passwords dont match!");
            FPass.setText("");
            FRPass.setText("");
        } else {

            try {
                String hashedPassword = Hash.generateStorngPasswordHash(
                       new String(FPass.getPassword()));
                int verify = ClientDAO.CreateClient(Fname.getText(),
                                                    FAddress.getText(),
                                                    Femail.getText(),
                                                    Fphone.getText(),
                                                    FNif.getText(),
                                                    hashedPassword);

                switch (verify) {
                    case EMAIL_ERROR_CODE ->
                        erro_create.setText(
                                "There's a user registered with that email already!");
                    case ERROR_CODE ->
                        erro_create.setText(
                                "Something unexpected happened, please try again later!");
                    case SUCCESS_CODE -> {
                        erro_create.setText("Success Creating the Client!");
                        SwingUtilities.invokeLater(() -> {
                            try {
                                Thread.sleep(1500);
                                panel.setSelectedIndex(0);
                                email_input.requestFocus();
                                email_input.setText(Femail.getText());
                            } catch (InterruptedException ex) {
                                System.out.println(ex);
                            }
                        });

                    }

                }

            } catch (NoSuchAlgorithmException | InvalidKeySpecException ex) {
                ex.printStackTrace(System.out);
            }
        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        panel.setSelectedIndex(0);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void seeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeActionPerformed
        if (see.isSelected()) {
            password_input.setEchoChar((char) 0);
        } else {
            password_input.setEchoChar('*');
        }
    }//GEN-LAST:event_seeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                         : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogLogin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogLogin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogLogin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogLogin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogLogin dialog = new dialogLogin(new javax.swing.JFrame(),
                                                     true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FAddress;
    private javax.swing.JTextField FNif;
    private javax.swing.JPasswordField FPass;
    private javax.swing.JPasswordField FRPass;
    private javax.swing.JTextField Femail;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Fphone;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel erro_create;
    private javax.swing.JLabel error;
    private javax.swing.JLabel image_1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressDot;
    private javax.swing.JLabel lblCreateAccount1;
    private javax.swing.JLabel lblDotEmail;
    private javax.swing.JLabel lblDotPassword;
    private javax.swing.JLabel lblDotPhone;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailDot;
    private javax.swing.JLabel lblFnameDot;
    private javax.swing.JLabel lblFphone;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLoginEmail;
    private javax.swing.JLabel lblLoginTitle;
    private javax.swing.JLabel lblNIF;
    private javax.swing.JLabel lblNifDot;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordDot;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRepeatPass;
    private javax.swing.JLabel lblRepeatPassDot;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JButton login;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel panelCreateAccount;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JCheckBox save_email;
    private javax.swing.JCheckBox see;
    // End of variables declaration//GEN-END:variables
}
