package pt.ua.ibank.interfaces;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import pt.ua.ibank.DAO.FuncionarioDAO;
import pt.ua.ibank.interfaces.internalFrames.ProfilePage;
import pt.ua.ibank.interfaces.internalFrames.StaffAccountList;
import pt.ua.ibank.interfaces.internalFrames.StaffManagerAccountList;
import pt.ua.ibank.interfaces.internalFrames.StaffManagercreateAccount;
import pt.ua.ibank.interfaces.internalFrames.StaffTransferList;
import static pt.ua.ibank.utilities.Configs.LocalFuncionario;
import pt.ua.ibank.utilities.DBConnection;
import static pt.ua.ibank.utilities.DBConnection.conn;
import pt.ua.ibank.utilities.MDIDesktopPane;
import pt.ua.ibank.utilities.RoundedShadowPanel;
import pt.ua.ibank.utilities.WindowMenu;

public class staffInterface extends javax.swing.JFrame {

    public static staffInterface localStaffInterface;
    public static Thread updateThread = null;
    private final String MANAGER_NAME = "Gerente";
    private final String EMPLOYEE_NAME = "Funcionario";

    public staffInterface() {
        try {
            initComponents();
            start_up();
        } catch (java.lang.NullPointerException e) {
            System.exit(1);
        }
    }

    private void start_up() {
        small_side_bar.setVisible(false);
        menu_bar.add(new WindowMenu((MDIDesktopPane) desktop));
        logout.setText("Fechar (" + LocalFuncionario.email + ")");
        updateInfo();
    }

    private void managerComponentsSetVisible(boolean aFlag) {
        btnCreateEmployeeAccount.setVisible(aFlag);
        createEmployeeAccount.setVisible(aFlag);
        btnManageEmployees.setVisible(aFlag);
        manageEmployees.setVisible(aFlag);
    }

    public void updateInfo() {
        lblEmployeeNameValue.setText(LocalFuncionario.nome);
        logout.setText("Fechar (" + LocalFuncionario.email + ")");
        lblsaccount.setText(LocalFuncionario.nome);
    }

    @Override
    public void dispose() {
        DBConnection.closeConnection(conn);
        updateThread = null;
    }

    public void addWindow(Component comp) {
        this.desktop.add(comp);
        center(comp);
        comp.setVisible(true);
        this.desktop.setComponentZOrder(comp, 0);
    }

    private void center(Component comp) {
        Dimension desktopSize = this.desktop.getSize();
        Dimension jInternalFrameSize = comp.getSize();
        comp.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                         (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        side_bar = new RoundedShadowPanel(5);
        jSeparator1 = new javax.swing.JSeparator();
        transferList = new javax.swing.JButton();
        accountlList = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPositionInCompany = new javax.swing.JLabel();
        lblsaccount = new javax.swing.JLabel();
        createEmployeeAccount = new javax.swing.JButton();
        manageEmployees = new javax.swing.JButton();
        ImageIcon backgroundImage = new ImageIcon(getClass().getResource("/resources/images/icons_20/background-otter-staff.png"));
        Image img = backgroundImage.getImage();
        desktop = new MDIDesktopPane(img);
        jPanelAccounts = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numContasCriadas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        nomeUltimaContaCriada = new javax.swing.JLabel();
        JPanelWidget3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        dataUltimoPedidoAprovacaoDeposito = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numDepositosAprovar = new javax.swing.JLabel();
        jPanelEmployeeOfMonth = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        numAprovacoesFeitas = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nomeFuncionarioMes = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblEmployeeNameValue = new javax.swing.JLabel();
        small_side_bar = new RoundedShadowPanel(5);
        btntransfers = new javax.swing.JButton();
        btnAccountlList = new javax.swing.JButton();
        btnaccount = new javax.swing.JButton();
        slogout = new javax.swing.JButton();
        btnCreateEmployeeAccount = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        menu_bar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        hide = new javax.swing.JMenuItem();

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("cargo");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuário");

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Bem vindo de volta,");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Nome");

        jLabel19.setText("IBank - Painel de Funcionário ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IBank");
        setBackground(new java.awt.Color(255, 255, 255));

        side_bar.setBackground(new java.awt.Color(252, 252, 255));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        transferList.setBackground(new java.awt.Color(62, 92, 118));
        transferList.setForeground(new java.awt.Color(240, 235, 216));
        transferList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/transacoes.png"))); // NOI18N
        transferList.setText("Ver Transferencias");
        transferList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transferList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferListActionPerformed(evt);
            }
        });

        accountlList.setBackground(new java.awt.Color(62, 92, 118));
        accountlList.setForeground(new java.awt.Color(240, 235, 216));
        accountlList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/account-list.png"))); // NOI18N
        accountlList.setText("Ver Lista de Contas");
        accountlList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        accountlList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountlListActionPerformed(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_24/logout.png"))); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_24/account_circle.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lblPositionInCompany.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lblPositionInCompany.setText(LocalFuncionario.isManager() ? MANAGER_NAME : EMPLOYEE_NAME);

        lblsaccount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblsaccount.setForeground(new java.awt.Color(62, 171, 191));
        lblsaccount.setText(LocalFuncionario.nome);
        lblsaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsaccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblsaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblsaccountMouseExited(evt);
            }
        });

        createEmployeeAccount.setBackground(new java.awt.Color(62, 92, 118));
        createEmployeeAccount.setForeground(new java.awt.Color(240, 235, 216));
        createEmployeeAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/addEmployee.png"))); // NOI18N
        createEmployeeAccount.setText("Criar conta de Funcionario");
        createEmployeeAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createEmployeeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployeeAccountActionPerformed(evt);
            }
        });

        manageEmployees.setBackground(new java.awt.Color(62, 92, 118));
        manageEmployees.setForeground(new java.awt.Color(240, 235, 216));
        manageEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/manage-users.png"))); // NOI18N
        manageEmployees.setText("Gerir funcionarios");
        manageEmployees.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout side_barLayout = new javax.swing.GroupLayout(side_bar);
        side_bar.setLayout(side_barLayout);
        side_barLayout.setHorizontalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_barLayout.createSequentialGroup()
                .addGroup(side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(side_barLayout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(14, 14, 14)
                        .addGroup(side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsaccount)
                            .addComponent(lblPositionInCompany))
                        .addGap(94, 94, 94))
                    .addGroup(side_barLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(side_barLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountlList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createEmployeeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        side_barLayout.setVerticalGroup(
            side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_barLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(side_barLayout.createSequentialGroup()
                        .addComponent(lblsaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblPositionInCompany))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(accountlList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferList, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createEmployeeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        jPanelAccounts.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAccounts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelAccounts.setMaximumSize(new java.awt.Dimension(238, 92));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/user.png"))); // NOI18N

        jLabel6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Contas criadas:");

        numContasCriadas.setBackground(new java.awt.Color(255, 255, 255));
        numContasCriadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numContasCriadas.setForeground(new java.awt.Color(62, 171, 191));
        numContasCriadas.setText(FuncionarioDAO.getNumContasCriadasMes().toString());

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Ultima conta criada:");

        nomeUltimaContaCriada.setBackground(new java.awt.Color(255, 255, 255));
        nomeUltimaContaCriada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeUltimaContaCriada.setText(FuncionarioDAO.getNomeUltimaContaCriada());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numContasCriadas)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeUltimaContaCriada))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numContasCriadas)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nomeUltimaContaCriada))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAccountsLayout = new javax.swing.GroupLayout(jPanelAccounts);
        jPanelAccounts.setLayout(jPanelAccountsLayout);
        jPanelAccountsLayout.setHorizontalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAccountsLayout.setVerticalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelWidget3.setBackground(new java.awt.Color(255, 255, 255));
        JPanelWidget3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JPanelWidget3.setMaximumSize(new java.awt.Dimension(238, 92));
        JPanelWidget3.setPreferredSize(new java.awt.Dimension(269, 124));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/deposit.png"))); // NOI18N

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ultimo pedido: ");

        dataUltimoPedidoAprovacaoDeposito.setBackground(new java.awt.Color(255, 255, 255));
        dataUltimoPedidoAprovacaoDeposito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dataUltimoPedidoAprovacaoDeposito.setText(FuncionarioDAO.getDataUltimoPedidoDeposito());

        jLabel10.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Depositos Por Aprovar:");

        numDepositosAprovar.setBackground(new java.awt.Color(255, 255, 255));
        numDepositosAprovar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numDepositosAprovar.setForeground(new java.awt.Color(62, 171, 191));
        numDepositosAprovar.setText(FuncionarioDAO.getNumDepositosPorAprovar().toString());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numDepositosAprovar)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataUltimoPedidoAprovacaoDeposito))
            .addComponent(jSeparator4)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numDepositosAprovar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(dataUltimoPedidoAprovacaoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout JPanelWidget3Layout = new javax.swing.GroupLayout(JPanelWidget3);
        JPanelWidget3.setLayout(JPanelWidget3Layout);
        JPanelWidget3Layout.setHorizontalGroup(
            JPanelWidget3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelWidget3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelWidget3Layout.setVerticalGroup(
            JPanelWidget3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelEmployeeOfMonth.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEmployeeOfMonth.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelEmployeeOfMonth.setMaximumSize(new java.awt.Dimension(238, 92));
        jPanelEmployeeOfMonth.setPreferredSize(new java.awt.Dimension(269, 124));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(291, 140));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/mvp-employee.png"))); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Operações feitas:");

        numAprovacoesFeitas.setBackground(new java.awt.Color(255, 255, 255));
        numAprovacoesFeitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numAprovacoesFeitas.setText(FuncionarioDAO.getNumAprovacoesFuncionarioTop().toString());

        jLabel20.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Moderador do mês:");

        nomeFuncionarioMes.setBackground(new java.awt.Color(255, 255, 255));
        nomeFuncionarioMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nomeFuncionarioMes.setForeground(new java.awt.Color(62, 171, 191));
        nomeFuncionarioMes.setText(FuncionarioDAO.getFuncionarioComMaisDepositosAprovados());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numAprovacoesFeitas))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(nomeFuncionarioMes)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeFuncionarioMes))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(numAprovacoesFeitas))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEmployeeOfMonthLayout = new javax.swing.GroupLayout(jPanelEmployeeOfMonth);
        jPanelEmployeeOfMonth.setLayout(jPanelEmployeeOfMonthLayout);
        jPanelEmployeeOfMonthLayout.setHorizontalGroup(
            jPanelEmployeeOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeOfMonthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanelEmployeeOfMonthLayout.setVerticalGroup(
            jPanelEmployeeOfMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeOfMonthLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        lblWelcome.setBackground(new java.awt.Color(0, 0, 0));
        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setText("Bem vindo de volta,");

        lblEmployeeNameValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmployeeNameValue.setText(LocalFuncionario.nome);

        desktop.setLayer(jPanelAccounts, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(JPanelWidget3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jPanelEmployeeOfMonth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lblWelcome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(lblEmployeeNameValue, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmployeeNameValue))
                    .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelAccounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPanelWidget3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addComponent(jPanelEmployeeOfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(604, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeNameValue)
                    .addComponent(lblWelcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanelAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(JPanelWidget3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanelEmployeeOfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        small_side_bar.setBackground(new java.awt.Color(252, 252, 255));
        small_side_bar.setVisible(false);

        btntransfers.setBackground(new java.awt.Color(62, 92, 118));
        btntransfers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/transacoes.png"))); // NOI18N
        btntransfers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btntransfers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransfersActionPerformed(evt);
            }
        });

        btnAccountlList.setBackground(new java.awt.Color(62, 92, 118));
        btnAccountlList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/account-list.png"))); // NOI18N
        btnAccountlList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAccountlList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountlListActionPerformed(evt);
            }
        });

        btnaccount.setBackground(new java.awt.Color(62, 92, 118));
        btnaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/employee-icon.png"))); // NOI18N
        btnaccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccountActionPerformed(evt);
            }
        });

        slogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_24/logout.png"))); // NOI18N
        slogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        slogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slogoutActionPerformed(evt);
            }
        });

        btnCreateEmployeeAccount.setBackground(new java.awt.Color(62, 92, 118));
        btnCreateEmployeeAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/addEmployee.png"))); // NOI18N
        btnCreateEmployeeAccount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateEmployeeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeAccountActionPerformed(evt);
            }
        });

        btnManageEmployees.setBackground(new java.awt.Color(62, 92, 118));
        btnManageEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/icons_20/manage-users.png"))); // NOI18N
        btnManageEmployees.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout small_side_barLayout = new javax.swing.GroupLayout(small_side_bar);
        small_side_bar.setLayout(small_side_barLayout);
        small_side_barLayout.setHorizontalGroup(
            small_side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(small_side_barLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(small_side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btntransfers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccountlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateEmployeeAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(slogout, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageEmployees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        small_side_barLayout.setVerticalGroup(
            small_side_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(small_side_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaccount)
                .addGap(31, 31, 31)
                .addComponent(btnAccountlList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntransfers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateEmployeeAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slogout)
                .addContainerGap())
        );

        jMenu1.setText("File");

        hide.setText("Esconder / Mostrar Menu");
        hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideActionPerformed(evt);
            }
        });
        jMenu1.add(hide);

        menu_bar.add(jMenu1);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(small_side_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(side_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(side_bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(small_side_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        switch (lblPositionInCompany.getText()) {
            case (MANAGER_NAME) -> {
                managerComponentsSetVisible(true);
            }
            default -> {
                managerComponentsSetVisible(false);
            }
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideActionPerformed
        if (side_bar.isVisible()) {
            side_bar.setVisible(false);
            small_side_bar.setVisible(true);
        } else {
            side_bar.setVisible(true);
            small_side_bar.setVisible(false);
        }
        System.out.println(LocalFuncionario.nome);
    }//GEN-LAST:event_hideActionPerformed

    private void btntransfersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransfersActionPerformed
        transferListActionPerformed(evt);
    }//GEN-LAST:event_btntransfersActionPerformed

    private void btnAccountlListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountlListActionPerformed
        accountlListActionPerformed(evt);
    }//GEN-LAST:event_btnAccountlListActionPerformed

    private void slogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slogoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_slogoutActionPerformed

    private void btnaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccountActionPerformed
        addWindow(new ProfilePage(LocalFuncionario));
    }//GEN-LAST:event_btnaccountActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        addWindow(new ProfilePage(LocalFuncionario));
    }//GEN-LAST:event_jLabel1MouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoutActionPerformed

    private void accountlListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountlListActionPerformed
        addWindow(new StaffAccountList(this));
    }//GEN-LAST:event_accountlListActionPerformed

    private void transferListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferListActionPerformed
        addWindow(new StaffTransferList(this));
    }//GEN-LAST:event_transferListActionPerformed

    private void lblsaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaccountMouseEntered
        jLabel1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lblsaccountMouseEntered

    private void lblsaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaccountMouseExited
        lblsaccount.setCursor(new Cursor(Cursor.HAND_CURSOR
        ));
    }//GEN-LAST:event_lblsaccountMouseExited

    private void lblsaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsaccountMouseClicked
        addWindow(new ProfilePage(LocalFuncionario));
    }//GEN-LAST:event_lblsaccountMouseClicked

    private void createEmployeeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployeeAccountActionPerformed
        addWindow(new StaffManagercreateAccount());
    }//GEN-LAST:event_createEmployeeAccountActionPerformed

    private void btnCreateEmployeeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeAccountActionPerformed
        createEmployeeAccountActionPerformed(evt);
    }//GEN-LAST:event_btnCreateEmployeeAccountActionPerformed

    private void manageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeesActionPerformed
        addWindow(new StaffManagerAccountList(this));
    }//GEN-LAST:event_manageEmployeesActionPerformed

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        manageEmployeesActionPerformed(evt);
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                         : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffInterface.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffInterface.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffInterface.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffInterface.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelWidget3;
    private javax.swing.JButton accountlList;
    private javax.swing.JButton btnAccountlList;
    private javax.swing.JButton btnCreateEmployeeAccount;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnaccount;
    private javax.swing.JButton btntransfers;
    private javax.swing.JButton createEmployeeAccount;
    private javax.swing.JLabel dataUltimoPedidoAprovacaoDeposito;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelAccounts;
    private javax.swing.JPanel jPanelEmployeeOfMonth;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblEmployeeNameValue;
    private javax.swing.JLabel lblPositionInCompany;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblsaccount;
    private javax.swing.JButton logout;
    private javax.swing.JButton manageEmployees;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JLabel nomeFuncionarioMes;
    private javax.swing.JLabel nomeUltimaContaCriada;
    private javax.swing.JLabel numAprovacoesFeitas;
    private javax.swing.JLabel numContasCriadas;
    private javax.swing.JLabel numDepositosAprovar;
    private javax.swing.JPanel side_bar;
    private javax.swing.JButton slogout;
    private javax.swing.JPanel small_side_bar;
    private javax.swing.JButton transferList;
    // End of variables declaration//GEN-END:variables
}
